spring:
  data:
    mongodb:
      database: NyReader
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    org.springframework:
      security: debug

jwt:
  token:
    header: Authorization
    secret: mySecret
    expiration: 600000

server:
  context-path:
