spring:
  data:
    mongodb:
      database: NyReader
  jackson:
    serialization:
      INDENT_OUTPUT: true
  mvc:
    favicon:
      enabled: false

logging:
  level:
    org.springframework:
      security: info

jwt:
  token:
    header: Authorization
    secret: mySecret
    expiration: 600000

server:
  context-path:
